// Code generated by protoc-gen-go.
// source: fs_data.proto
// DO NOT EDIT!

/*
Package fs_data is a generated protocol buffer package.

It is generated from these files:
	fs_data.proto

It has these top-level messages:
	FSFact
	FSSource
	FamilySearchPerson
	FamilySearchPersons
*/
package fs_data

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type FSGender int32

const (
	FSGender_MALE    FSGender = 1
	FSGender_FEMALE  FSGender = 2
	FSGender_UNKNOWN FSGender = 3
)

var FSGender_name = map[int32]string{
	1: "MALE",
	2: "FEMALE",
	3: "UNKNOWN",
}
var FSGender_value = map[string]int32{
	"MALE":    1,
	"FEMALE":  2,
	"UNKNOWN": 3,
}

func (x FSGender) Enum() *FSGender {
	p := new(FSGender)
	*p = x
	return p
}
func (x FSGender) String() string {
	return proto.EnumName(FSGender_name, int32(x))
}
func (x *FSGender) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FSGender_value, data, "FSGender")
	if err != nil {
		return err
	}
	*x = FSGender(value)
	return nil
}

type FSFact struct {
	Type             *string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Year             *int32  `protobuf:"varint,2,opt,name=year" json:"year,omitempty"`
	Place            *string `protobuf:"bytes,3,opt,name=place" json:"place,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FSFact) Reset()         { *m = FSFact{} }
func (m *FSFact) String() string { return proto.CompactTextString(m) }
func (*FSFact) ProtoMessage()    {}

func (m *FSFact) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *FSFact) GetYear() int32 {
	if m != nil && m.Year != nil {
		return *m.Year
	}
	return 0
}

func (m *FSFact) GetPlace() string {
	if m != nil && m.Place != nil {
		return *m.Place
	}
	return ""
}

type FSSource struct {
	SourceId         *string `protobuf:"bytes,1,opt,name=source_id" json:"source_id,omitempty"`
	Title            *string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FSSource) Reset()         { *m = FSSource{} }
func (m *FSSource) String() string { return proto.CompactTextString(m) }
func (*FSSource) ProtoMessage()    {}

func (m *FSSource) GetSourceId() string {
	if m != nil && m.SourceId != nil {
		return *m.SourceId
	}
	return ""
}

func (m *FSSource) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

type FamilySearchPerson struct {
	Id               *string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Gender           *FSGender   `protobuf:"varint,2,opt,name=gender,enum=fs_data.FSGender" json:"gender,omitempty"`
	Facts            []*FSFact   `protobuf:"bytes,3,rep,name=facts" json:"facts,omitempty"`
	Contributors     []string    `protobuf:"bytes,4,rep,name=contributors" json:"contributors,omitempty"`
	Sources          []*FSSource `protobuf:"bytes,5,rep,name=sources" json:"sources,omitempty"`
	Parents          []string    `protobuf:"bytes,6,rep,name=parents" json:"parents,omitempty"`
	Spouses          []string    `protobuf:"bytes,7,rep,name=spouses" json:"spouses,omitempty"`
	Children         []string    `protobuf:"bytes,8,rep,name=children" json:"children,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *FamilySearchPerson) Reset()         { *m = FamilySearchPerson{} }
func (m *FamilySearchPerson) String() string { return proto.CompactTextString(m) }
func (*FamilySearchPerson) ProtoMessage()    {}

func (m *FamilySearchPerson) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *FamilySearchPerson) GetGender() FSGender {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return FSGender_MALE
}

func (m *FamilySearchPerson) GetFacts() []*FSFact {
	if m != nil {
		return m.Facts
	}
	return nil
}

func (m *FamilySearchPerson) GetContributors() []string {
	if m != nil {
		return m.Contributors
	}
	return nil
}

func (m *FamilySearchPerson) GetSources() []*FSSource {
	if m != nil {
		return m.Sources
	}
	return nil
}

func (m *FamilySearchPerson) GetParents() []string {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *FamilySearchPerson) GetSpouses() []string {
	if m != nil {
		return m.Spouses
	}
	return nil
}

func (m *FamilySearchPerson) GetChildren() []string {
	if m != nil {
		return m.Children
	}
	return nil
}

type FamilySearchPersons struct {
	Persons          []*FamilySearchPerson `protobuf:"bytes,1,rep,name=persons" json:"persons,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *FamilySearchPersons) Reset()         { *m = FamilySearchPersons{} }
func (m *FamilySearchPersons) String() string { return proto.CompactTextString(m) }
func (*FamilySearchPersons) ProtoMessage()    {}

func (m *FamilySearchPersons) GetPersons() []*FamilySearchPerson {
	if m != nil {
		return m.Persons
	}
	return nil
}

func init() {
	proto.RegisterEnum("fs_data.FSGender", FSGender_name, FSGender_value)
}
